tasks:
  - init:
      bundle install &&
      yarn &&
      bundle exec rake db:migrate &&
      git checkout -b experiment-1 &&
    command:
      bundle exec foreman start
ports:
  - port: 5000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
  - port: 9514
    onOpen: ignore
  - port: 9515
    onOpen: ignore
  - port: 25222
    onOpen: ignore
